T3-13 Base functionality completed. First review
SidorovKV/java-shareit pull request #1
Opened 2023-05-16 19:20 UTC by SidorovKV

2023-05-17 20:45 UTC, alexache requested changes

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/InMemItemRepo.java
> + * реализацию кажется излишним.
Все так, интерфейс не требуется

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/InMemItemRepo.java
> +        return items.values().stream().filter(item -> item.getOwnerId() == ownerId).collect(Collectors.toList());
Не очень оптимально, может стоит использовать еще одну мапу и хранить маппинг юзера на список его вещей?

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/InMemItemRepo.java
> +                                        item.getName().toLowerCase().contains(text.toLowerCase()) ||
text.toLowerCase можно посчитать единожды

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/InMemItemRepo.java
> +                ).collect(Collectors.toCollection(() -> new TreeSet<>(Comparator.comparing(Item::getId))));
А зачем это в сет. разве айди и так не уникален?

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
injection через конструктор предпочтительнее чем через поле

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
Здесь скорее нужен будет объект ItemRequest

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
А здесь объект User

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
Где-то есть @Autowired: где-то нет, Лучше что-то одно

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userRepository.findById(ownerId).isEmpty()) {
Почему не через orElseThrow как в других местах?

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/InMemUserRepo.java
> +    private final HashMap<Long, User> userRepo = new HashMap<>();
Лучше исползовать интерфейс в качестве типа у поля нежели конкретную реализацию

2023-05-17 20:45 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/InMemUserRepo.java
> +        if (userRepo.containsKey(id)) {
немного интерфейс слишком похож на мапу и выдает то, какая там реализация, можно обойтись и просто методом получения сущности по айди

2023-05-18 12:11 UTC, SidorovKV commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userRepository.findById(ownerId).isEmpty()) {
Потому что не нужна была сама сущность Юзер. Теперь, после изменения в модели Айтем, будет нужна

2023-05-29 12:04 UTC, merged