Add bookings
SidorovKV/java-shareit pull request #2
Opened 2023-06-02 13:48 UTC by SidorovKV

Основной функционал готов ТЗ 14 готов. Некоторые места кажутся неэффективными, но понять, как сделать их более эффективными на ORM, не удалось.

2023-06-03 16:22 UTC, alexache requested changes

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +    private UserDto booker;
Лучше делать вложенные упрощенные ДТО, нежели ссылаться на другие полноценные ДТО по той причине, что там могут быть какие-то дополнительные лишние поля

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new WierdNotFoundException(//Почему-то тесты ждут здесь 404 ошибку
Вероятно предполагается, что метод выше bookingRepository.findById на самом деле может быть findByidAndItemOwnerId() - то есть ищется по айди бронирования и владельцу вещи одним запросом

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ForBookingItemDto.java
> +public class ForBookingItemDto {
ItemDtoForBooking?

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    setLastAndNextBooking(item);
Это запросы к базе в цикле, их нужно избегать - разбивать на несколько запросов, но "батч" запросы, чтобы получать требуемые сущности по списку айдишников

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    List<Comment> comments = commentRepository.findAllByItemId(item.getId());
Как и этот запрос - тоже запрос внутри цикла

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                booking -> booking.getItem().getId() == itemId
А если у пользователя очень много бронирований? Почему бы в запросе выше не использовать getItem().getId()?

2023-06-03 16:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static void userUpdateFromUpdateDto(User user, UserUpdateDto userUpdateDto) {
Это не очень похоже на работу маппера, а значит излишне для этого класса

2023-06-03 16:22 UTC, alexache commented on src/main/resources/schema.sql
> +    name varchar   NOT NULL,
Лучше для всех varchar указывать лимит по количеству символов

2023-06-03 17:16 UTC, SidorovKV commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +            if (booking.getBooker() == null) {
Сначала именно так и делал, но помню, что это вызывало ошибки в промежуточных прогонах тестов. Сейчас вернул к тернарному и тесты прошли хорошо. Видимо проблема когла-то тогда была не в маппере)

2023-06-03 20:27 UTC, SidorovKV commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    List<Comment> comments = commentRepository.findAllByItemId(item.getId());
Получился какой-то монстр) Ощущение, что более изящное решение ускользает от меня

2023-06-04 18:53 UTC, alexache approved these changes

2023-06-04 18:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Booking> bookings = bookingRepository.findAllByItemIdInAndItemOwnerIdAndStatus(itemIds, ownerId, Status.APPROVED);
(опционально) Наверное будет немного проще, если бронирования будут сгруппированны по вещам. В рамках таких списков на вещь будет нагляднее обход бронирований и сортировка их по датам начала/окончания/фильтрации

2023-06-04 18:53 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoForBooking.java
> +public class UserDtoForBooking {
(опционально) Я даже больше про вложенные классы, то есть class BookingDto { class UserDto {} }

2023-06-05 10:36 UTC, merged