Add item requests
SidorovKV/java-shareit pull request #3
Opened 2023-06-18 11:13 UTC by SidorovKV

ТЗ-15
Запрошенный функционал.
Тесты... Много тестов. (Непонятно почему их не ввели в 13 ТЗ, которое очень маленькое)

2023-06-19 18:07 UTC, alexache requested changes

2023-06-19 18:07 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        ArgumentCaptor<ItemDto> argumentCaptor = ArgumentCaptor.forClass(ItemDto.class);
Не уверен, что стоит концентрироваться на аргументах, передаваемых в сервис. Может стоит немного больше уделять тому, что контроллер вернет обратно: полноценности полей в респонсе

2023-06-19 18:25 UTC, SidorovKV commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=ci,test,default
Почему-то если не добавить дефолтный профиль или вообще не закомментить эту строку, то локально работа с базой проходит криво. Например constraint unique не отрабатывает. 
В принципе можно и убрать, так как только локально мне нужно было

2023-06-19 18:26 UTC, SidorovKV commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void whenInvalidPostRequestThenBadRequest() throws Exception {
OMG... Хорошо

2023-06-20 14:28 UTC, SidorovKV commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        ArgumentCaptor<ItemDto> argumentCaptor = ArgumentCaptor.forClass(ItemDto.class);
В одном из материалов прочитал, что тест вызова логики из контроллера лучше делать.
Проверку выходных джейсонов добавил во все контроллеры.

2023-06-20 14:31 UTC, SidorovKV commented
Тест ДатаЖпа для поиска добавил, проглядел в тз. Кажется одиноким))
Наверное, правильно было бы прописать для всех своих запросных методов тесты, но тз не требует этого.

2023-06-20 18:02 UTC, alexache commented on src/main/resources/application.properties
> +spring.config.activate.on-profile=ci,test,default
локально ты указываешь профиль test при запуске?

2023-06-20 18:05 UTC, alexache approved these changes

2023-06-23 13:20 UTC, merged