Add docker
SidorovKV/java-shareit pull request #4
Opened 2023-06-25 21:05 UTC by SidorovKV

2023-06-26 19:52 UTC, SidorovKV commented
Почему-то локально не работает сетевое взаимодействие контейнеров при запуске через docker-compose.
Нашёлся обход через podman + podman-compose. Не очень понимаю, в чём проблема с докером. Система ArchLinux

2023-06-27 07:46 UTC, alexache requested changes

2023-06-27 07:46 UTC, alexache commented on gateway/src/main/resources/application.properties
> +#logging.level.org.springframework=TRACE
Закомментированный код лучше убрать

2023-06-27 07:46 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +            //@Valid
Лучше просто удалить

2023-06-27 07:46 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/utils/ErrorHandler.java
> +    /*@ExceptionHandler
Тоже лучше удалить

2023-06-27 09:24 UTC, SidorovKV commented on server/src/main/java/ru/practicum/shareit/utils/ErrorHandler.java
> +    /*@ExceptionHandler
Подчистил закомментированный код в указанных местах и ещё в паре мест. Забыл об этом. Sorry.

2023-06-27 18:36 UTC, alexache approved these changes

2023-06-28 10:32 UTC, merged